### ISSUE TITLE
Resettable integral action 

### ISSUE THREAD

**Issue by pedsancue** [grvcTeam/Firmware#15]
Add resettable integral action to the UAV controller to validate if it works with the diverse time executions in NUC/RaspberryPi

**Comment by crdecos** [comment]
NUCControl_v7 with integral action resetting on take off.
[NUCControl_v7.zip](https://github.com/grvcTeam/Firmware/files/1551031/NUCControl_v7.zip)

**Comment by crdecos** [comment]
**Experiments with 15% thrust resetting** 
The reset worked, but we realised that the integral action produced problems between the arming of the UAV and the 15% thrust level. The momentary solution was to arm the UAV in PX4, get over the 15% thrust and then pass to the NUC controller. However, the solution of this problem is to deactivate the integral action with thrust bellow 15% (gain zero and reset of the integral action when passing this level). _Experiments to validate this solution must be carried out soon._

**Comment by agr695** [comment]
We have see that it is necessary send timestamp as float because matlab cannot receive an unsigned integer. However in matlab, we work with single, this can be a problem in the future because of the low precision and some overflow problem. 

Apart of this, the timestamp is sent as the last data of every module we use.

**Comment by jaarhu** [comment]
Ok guys let's write in english! Integrators are difficult in matlab, believe me. So, please, for the next experiment, with simulink controller, save the following: 
1) the time in both simulink and raspi. For what you said, Antonio, I suppose that's possible.
2) Signals before and after the Rate Transition blocks.
3) The error before and after the integral part of the PID, I mean in the input and the output of the integral. Maybe you cannot do it with the block you're using for the PID, in that case the input and output of the block, for now.

Give me all the records, please and thanks ;)

**Comment by crdecos** [comment]
This version includes the signal recording, but the time data has not still been added. As you mentioned, the data obtained from the PID is limited to the error input and the PID output (taking into account the modifications to the integral action). 
[NUCControl_v7_1.zip](https://github.com/grvcTeam/Firmware/files/1559004/NUCControl_v7_1.zip)

**Comment by jaarhu** [comment]
Thanks. What's happening with the time? Manu/Antonio. Problems?

**Comment by crdecos** [comment]
** Experiments Resettable Integral action without timestamp **

The experiment __ exp_6_NUCControl_v7_14_12_17_2_cuerda __
